# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='owner',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='musicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
