# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(
                default=b'blog_icons/7tennis.jpg', upload_to=b'blog_icons'),
        ),
    ]
