# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 15:28
from __future__ import unicode_literals

import common.arrayfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160515_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='path',
            field=common.arrayfields.IntegerArrayField(
                blank=True, editable=False),
        ),
    ]
