# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20160519_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(
                b'Male', b'Male'), (b'Female', b'Female')], max_length=140, null=True),
        ),
    ]
